### ISSUE TITLE
Deprecate `errcode(String, ...)`

### ISSUE THREAD

**Issue by achingbrain** [IndigoUnited/js-err-code#19]
If you pass a string as the first argument, this module will new up an `Error` for us, which is convenient and all but means the stack trace for the error starts in the `err-code` module and not at the throw site.

This leads to developer confusion as there are irrelevant lines in the stack trace, and also leaks internal implementation details of the calling code (e.g. that `err-code` is used) which seems like an anti-pattern.

Accepting a string as the first argument should be deprecated and removed in a future release in favour of passing in `Error` objects.

What do you think?

**Comment by satazor** [comment]
I agree! Let’s remove the support for it as a breaking change and bump the major. Wanna do a PR?

**Comment by achingbrain** [comment]
Done!  See #20

**Comment by gabssnake** [comment]
Hi there !
Have you considered using [`Error.captureStackTrace`](https://stackoverflow.com/a/67073333/1585841) to provide `String` support without the additional stack entry ?
Happy to propose some code if you're open to that :)
Best,
